Este es mi Assignment2
FacultadInformatica-LinkedData/Curso2021-2022 pull request #128
Opened 2021-09-16 20:56 UTC by vcuende

2021-09-17 17:00 UTC, ocorcho requested changes

2021-09-17 17:00 UTC, ocorcho commented on Assignment2/vcuende-VictorMorcuende.ttl
> +:Measurement8401 fi:hasTemperature "29" ;
Add datatypes, here and in the next line

2021-09-19 16:55 UTC, vcuende reviewed
Assignment is updated

2021-09-24 18:05 UTC, ocorcho commented
No subas el .DS_Store. Se debe ignorar para no generar problemas.

2021-09-24 18:06 UTC, merged