Add files via upload
FacultadInformatica-LinkedData/Curso2021-2022 pull request #129
Opened 2021-09-16 21:11 UTC by aruizgar21

2021-09-17 15:19 UTC, ocorcho commented
Next time, please do it using git instead of the GitHub interface

2021-09-17 15:22 UTC, ocorcho requested changes

2021-09-17 15:22 UTC, ocorcho commented on Assignment2/aruizgar21-AntonioRuiz.ttl
> +@prefix : <http://ex.org/#> .
there should be a prefix name

2021-09-17 15:22 UTC, ocorcho commented on Assignment2/aruizgar21-AntonioRuiz.ttl
> +:Class01 rdfs:includes:Computer101;
Space should be added between includes and :Computer101

2021-09-17 15:22 UTC, ocorcho commented on Assignment2/aruizgar21-AntonioRuiz.ttl
> +:Class01 rdfs:includes:Computer101;
And rdfs:includes is wrong.

2021-09-17 15:22 UTC, ocorcho commented on Assignment2/aruizgar21-AntonioRuiz.ttl
> +:Measurement8401 rdfs:hasTemperature "29";
You should add a datatype

2021-09-17 15:22 UTC, ocorcho commented on Assignment2/aruizgar21-AntonioRuiz.ttl
> +rdfs:atTime "2010-06-12T12:00:12".
You should add a datatype

2021-09-17 15:22 UTC, ocorcho commented on Assignment2/aruizgar21-AntonioRuiz.ttl
> +:Computer101 rdfs:hasOwner:User10A.
Same problem with the space

2021-09-17 15:22 UTC, ocorcho commented on Assignment2/aruizgar21-AntonioRuiz.ttl
> +:User10A rdfs:hasName "Pedro" ;
Will it parse?

2021-09-19 16:54 UTC, aruizgar21 reviewed
Changed

2021-09-24 18:04 UTC, merged