Upload of Individual Assignment2a
FacultadInformatica-LinkedData/Curso2021-2022 pull request #149
Opened 2021-09-17 15:08 UTC by MarcoAS99

Upload of Individual Assignment2a

2021-09-17 15:34 UTC, ocorcho requested changes

2021-09-17 15:34 UTC, ocorcho commented on Assignment2/Marco_turtle.ttl
> +@prefix cl: <http://www.oeg-upm.net/Class01#/>.
No /# should be used

2021-09-17 15:34 UTC, ocorcho commented on Assignment2/Marco_turtle.ttl
> +@prefix m: <http://www.oeg-upm.net/Measurement8401#/>.
Needed?

2021-09-20 13:18 UTC, MarcoAS99 commented
Assignment reviewed.

2021-09-25 10:02 UTC, ocorcho requested changes

2021-09-25 10:02 UTC, ocorcho commented on Assignment2/MarcoAS99-fromRDFtoJSON-LD.jsonld
> +            "@type": "rec",
You are using types wrongly

2021-09-25 10:02 UTC, ocorcho commented
Assignment 2a ok, request for changes in 2b

2021-10-02 11:18 UTC, closed without merging