Assignment2b done
FacultadInformatica-LinkedData/Curso2021-2022 pull request #166
Opened 2021-09-19 21:53 UTC by polkiko

2021-09-24 18:11 UTC, ocorcho requested changes
Some examples provided

2021-09-24 18:11 UTC, ocorcho commented on Assignment2/polkiko-fromRDFtoJSON-LD.jsonld
> +          "@type": "rdfs:Class",
This should not be the type of this object. It should be something different.

2021-09-24 18:11 UTC, ocorcho commented on Assignment2/polkiko-fromRDFtoJSON-LD.jsonld
> +          "@type": "rdfs:Class",
Same here, it should be a Computer class

2021-09-24 20:49 UTC, polkiko reviewed
Change in classes

2021-09-25 09:56 UTC, ocorcho approved these changes

2021-09-25 09:56 UTC, ocorcho commented on Assignment2/polkiko-fromRDFtoJSON-LD.jsonld
> +        "@type": "rdfs:Measurement",
Should not be rdfs:Measurement, since it is not describe in RDF Schema, but I accept it.

2021-09-25 09:56 UTC, merged