Assignment 4 donde
FacultadInformatica-LinkedData/Curso2021-2022 pull request #212
Opened 2021-09-27 13:58 UTC by ssolana

I couldn't upload the assignment 4 files into a new pull request, because my first pull request from assignment2 hadn't been accepted, in order to not losing the assignment2 files i have to upload them all with the assignment4 files, I'm sorry i couldn't find any other option

2021-09-27 14:10 UTC, ocorcho commented
Assignment 2a and 2b are now ok

2021-10-05 16:23 UTC, dgarijo commented on Assignment4/ssolana-a180262/task06.py
> +!pip install rdflib
This line has to be commented out in order for the script to work

2021-10-05 16:24 UTC, dgarijo commented on Assignment4/ssolana-a180262/task07.py
> +    ?Subject(rdfs:subClassOf/rdfs:subClassOf*) ns:Person
This is equivalent to just having rdfs:subClassOf+

2021-10-05 16:26 UTC, dgarijo commented on Assignment4/ssolana-a180262/task07.py
> +        ?Subject ?p ?o
This is wrong. It should be ?subject3, or otherwise you are binding all triples in the graph

2021-10-05 16:26 UTC, dgarijo commented
Please fix the main typo in the last query

2021-11-02 14:12 UTC, dgarijo requested changes
Please see my comments to address current issues

2021-11-15 09:40 UTC, dgarijo commented
Requested changes have not been implemented. Closing this PR

2021-11-15 09:40 UTC, closed without merging