Assignment 4
FacultadInformatica-LinkedData/Curso2021-2022 pull request #241
Opened 2021-09-28 20:16 UTC by alb433

2021-10-04 08:58 UTC, rgcmme commented
* The name of the directory of the HandsOn is not correct.
* All the dataset requirements must be in a single HTML document.

Implement these changes and the pull request will be updated with them.

2021-10-05 18:48 UTC, dgarijo commented on Assignment4/alb433-150213/task06.py
> +!pip install rdflib
this won't work in Python. Please comment this line

2021-10-05 19:03 UTC, dgarijo commented on Assignment4/alb433-150213/task07.py
> +
Missing how to do this in rdflib

2021-10-05 19:08 UTC, dgarijo commented on Assignment4/alb433-150213/task07.py
> +
Missing how to do 7.3 in SPARQL

2021-10-05 19:09 UTC, dgarijo commented
See missing/errors above for assignment 4

2021-11-02 14:14 UTC, dgarijo requested changes
See inline comments regarding the pending issues

2021-11-15 09:43 UTC, dgarijo commented
Requested changes have not been implemented. Closing this PR

2021-11-15 09:43 UTC, closed without merging